config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: "registrations"}
  namespace :teachers do
    resources :questions
    resources :log_exams, only: [:index, :show, :update, :destroy]
    resources :exams do
      collection do
        get :search
      end
    end
    resources :subjects, only: :show
  end

  namespace :students do
    resources :exams, only: :index
    resources :log_exams, except: [:new, :destroy]
  end

  root "application#index"
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  has_many :answers, dependent: :destroy
  has_many :exam_questions, dependent: :destroy
  has_many :exams, through: :exam_questions
  has_many :log_questions

  validates :subject, presence: true,
    length: {maximum: Settings.validations.strings.max_length}
  validates :content, presence: true,
    length: {maximum: Settings.validations.texts.max_length}

  accepts_nested_attributes_for :answers, reject_if: :check_option
  mount_uploader :file, FileUploader

  private
  def check_option
    self.answers.any? {|answer| answer.option.blank?}
  end
end

app/controllers/teachers/exams_controller.rb
module Teachers
  class ExamsController < ApplicationController
    before_action :find_exam, only: [:show, :edit, :update, :destroy]
    before_action :check_permission

    def index
      @exams = Exam.all
    end

    def show ; end

    def new
      @exam = Exam.new
      @questions = Question.all
    end

    def create
      @exam = Exam.new exam_params
      @exam.user = current_user
      if @exam.save
        redirect_to teachers_exams_path
      else
        @questions = Question.all
        render :new
      end
    end

    def edit
      @questions = Question.all
    end

    def update
      if @exam.update_attributes(exam_params)
        redirect_to teachers_exam_path
      else
        @questions = Question.all
        render :edit
      end
    end

    def destroy
      @exam.destroy
      redirect_to teachers_exams_path
    end

    def search
      @exams = Question.find(params[:id]).exams
    end

    private
    def exam_params
      params.require(:exam).permit(:name, :time_for_exam, question_ids: [])
    end

    def find_exam
      @exam = Exam.find params[:id]
    end

    def check_permission
      case params[:action]
      when "index", "show"
        redirect_to root_path if cannot? :read, Exam
      when "new", "create"
        redirect_to root_path if cannot? :create, Exam
      when "edit", "update", "destroy"
        redirect_to root_path if @exam.user != current_user
      end
    end
  end
end

app/controllers/teachers/log_exams_controller.rb
module Teachers
  class LogExamsController < ApplicationController
    before_action :find_log_exam, only: [:show, :update, :destroy]
    before_action :check_permission

    def index
      @log_exams = LogExam.own_submitted_log_exams current_user.id
    end

    def show
      @exam = @log_exam.exam
    end

    def update
      @log_exam.update_attributes! status: :approved
      redirect_to teachers_exams_path
    end

    def destroy
      @log_exam.destroy
      redirect_to teachers_exams_path
    end

    private
    def find_log_exam
      @log_exam = LogExam.find params[:id]
    end

    def check_permission
      case params[:action]
      when "index", "show"
        redirect_to root_path if cannot? :read, LogExam
      when "update", "destroy"
        redirect_to root_path if @log_exam.exam.user != current_user
      end
    end
  end
end

app/controllers/teachers/questions_controller.rb
module Teachers
  class QuestionsController < ApplicationController
    before_action :find_question, only: [:show, :edit, :update, :destroy]
    before_action :check_permission

    def index
      @questions = Question.all
    end

    def show ; end

    def new
      @question = current_user.questions.new
      4.times {@question.answers.build}
    end

    def create
      @question = current_user.questions.new question_params
      if @question.save
        redirect_to teachers_questions_path
      else
        render :new
      end
    end

    def edit ; end

    def update
      if @question.update_attributes question_params
        redirect_to teachers_questions_path
      else
        render :edit
      end
    end

    def destroy
      @question.destroy
      redirect_to teachers_questions_path
    end

    private
    def question_params
      params.require(:question).permit(:subject_id, :content, :file,
        answers_attributes: [:is_true, :option, :id])
    end

    def find_question
      @question = Question.find params[:id]
    end

    def check_permission
      case params[:action]
      when "index", "show"
        redirect_to root_path if cannot? :read, Question
      when "new", "create"
        redirect_to root_path if cannot? :create, Question
      when "edit", "update", "destroy"
        redirect_to root_path if @question.user != current_user
      end
    end
  end
end

app/controllers/teachers/subjects_controller.rb
module Teachers
  class SubjectsController < ApplicationController
    def show
      @questions = Subject.find(params[:id]).questions
    end
  end
end

app/helpers/teachers/log_exams_helper.rb
module Teachers
  module LogExamsHelper
    def exam_requested exam_id
      @log_exams = LogExam.where exam_id: exam_id, teacher_id: current_user.id, status: :requested
    end
  end
end

app/views/teachers/questions/_answer_fields.html.erb
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <div class="input-group-text">
      <%= f.check_box :is_true, {}, true, false %>
    </div>
  </div>
  <%= f.text_field :option, class: 'form-control', placeholder: 'Enter the answer', value: answer ? answer.option : "" %>
</div>

app/views/teachers/questions/edit.html.erb
<div class="w-50 m-auto">
  <h2 class="text-center mt-5">Edit question</h2>
  <% if @question.errors.any? %>
    <ul class="list-group list-group-flush">
      <% @question.errors.full_messages.each do |msg| %>
        <li class="list-group-item allert alert-danger"><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_for(@question, url: teachers_question_path(@question)) do |f| %>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.select :subject_id, Subject.all.collect {|subject| [subject.name, subject.id]}, {}, {class: "custom-select", selected: @question.subject.id} %>
    </div>

    <div class="form-group">
      <%= f.label :content, "Question" %>
      <%= f.text_area :content, class: "form-control", placeholder: "Enter the question", value: @question.content, rows: 5 %>
    </div>

    <div class="form-group">
      <%= f.label :file %>
      <div class="custom-file">
        <%= f.file_field :file, class: "custom-file-input", value: @question.file, onchange: "displayFileName()" %>
        <%= f.label :file, @question.file.nil? ? "Choose file" : @question.file.to_s.split("/").pop, class: "custom-file-label" %> <br>
      </div>
    </div>

    <div class="form-group">
      <label>Answers</label>
      <% @question.answers.each do |answer| %>
        <%= f.fields_for :answers, answer do |ff| %>
          <%= render "answer_fields", f: ff, answer: answer %>
        <% end %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.submit "Update", class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
</div>

app/views/teachers/questions/index.html.erb
<% @questions.each do |question| %>
  <div class="shadow-lg p-4 mb-4 bg-white" style="border-radius: 1em">
    <h3><%= link_to truncate(question.content, length: 75), teachers_question_path(question) %></h3>
    <small><%= pluralize question.answers.count, "answer" %>,
      <%= pluralize question.file.blank? ? 0 : 1 , "file attachment" %>,
      updated by <%= question.user.name %>
      at <%= time_ago_in_words question.updated_at %></small>
      <br>
      <span class="badge badge-info">
        <%= link_to("Used #{pluralize(question.exams.count, "time")}",
        search_teachers_exams_path(id: question.id), class: "text-light")%>
      </span>
      <span class="badge badge-success"><%= link_to question.subject.name, teachers_subject_path(question.subject), class: "text-light"%></span>
    <% if question.user == current_user %>
      <ul class="breadcrumb pl-0" style="background-color: rgba(0,0,0,0)">
        <li class="breadcrumb-item"><%= link_to "Edit", edit_teachers_question_path(question) %></li>
        <li class="breadcrumb-item"><%= link_to "Delete", teachers_question_path(question), method: :delete %></li>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/teachers/questions/new.html.erb
<div class="w-50 m-auto">
  <h2 class="text-center mt-5">Create new question</h2>
  <% if @question.errors.any? %>
    <ul class="list-group list-group-flush">
      <% @question.errors.full_messages.each do |msg| %>
        <li class="list-group-item allert alert-danger"><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_for(@question, url: teachers_questions_path(current_user)) do |f| %>
    <div class="form-group">
      <%= f.label :subject_id %>
      <%= f.select :subject_id, Subject.all.collect {|subject| [subject.name, subject.id]}, {}, {class: "custom-select"} %>
    </div>

    <div class="form-group">
      <%= f.label :content, "Question" %>
      <%= f.text_area :content, class: "form-control", placeholder: "Enter the question", rows: 5 %>
    </div>

    <div class="form-group">
      <%= f.label :file %>
      <div class="custom-file">
        <%= f.file_field :file, class: "custom-file-input", onchange: "displayFileName()" %>
        <%= f.label :file, "Choose file", class: "custom-file-label" %> <br>
      </div>
    </div>

    <div class="form-group">
      <label>Answers</label>
      <%= f.fields_for :answers do |ff| %>
        <%= render "answer_fields", f: ff, answer: nil %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.submit "Create", class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
</div>

app/views/teachers/questions/show.html.erb
<div class="shadow-lg p-4 mb-4 bg-white" style="border-radius: 1em">
  <span><b>Question: </b></span>
  <span class="text-justify"><%= @question.content %></span>
  <div class="ml-4">
    <span class="badge badge-info">
      <%= link_to("Used #{pluralize(@question.exams.count, "time")}",
      search_teachers_exams_path(id: @question.id), class: "text-light")%>
    </span>
    <span class="badge badge-success"><%= link_to @question.subject.name, teachers_subject_path(@question.subject), class: "text-light"%></span>
    <span class="badge badge-info">
      <%= link_to "File attachment", @question.file_url, class: "text-light" %>
    </span>
    <br>
    <div class="card border-0">
      <div class="card-body p-0">
        <ul class="list-group list-group-flush">
          <% @question.answers.each do |answer| %>
            <% if answer.is_true %>
              <li class="list-group-item custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="customCheck" name="example1" disabled checked>
                <label class="custom-control-label text-dark" for="customCheck"><%= answer.option %></label>
              </li>
            <% else %>
              <li class="list-group-item">
                <input type="checkbox" class="custom-control-input" id="customCheck" name="example1" disabled>
                <label class="custom-control-label text-dark" for="customCheck"><%= answer.option %></label>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>