config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: "registrations"}
  namespace :teachers do
    resources :questions
    resources :log_exams, only: [:index, :show, :update, :destroy]
    resources :exams do
      collection do
        get :search
      end
    end
    resources :subjects, only: :show
  end

  namespace :students do
    resources :exams, only: :index
    resources :log_exams, except: [:new, :destroy]
  end

  root "application#index"
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="#">Logo</a>
  <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <% if current_user.teacher? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Question</a>
          <div class="dropdown-menu">
            <%= link_to "Questions list", teachers_questions_path, class: "dropdown-item" %>
            <%= link_to "New question", new_teachers_question_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Exam</a>
          <div class="dropdown-menu">
            <%= link_to "Exams list", teachers_exams_path, class: "dropdown-item" %>
            <%= link_to "New exam", new_teachers_exam_path, class: "dropdown-item" %>
            <%= link_to "Review answered exams", teachers_log_exams_path, class: "dropdown-item" %>
          </div>
        </li>
      <% elsif %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Exam</a>
          <div class="dropdown-menu">
            <%= link_to "Exams list", students_exams_path, class: "dropdown-item" %>
            <%= link_to "Review answered exams", students_log_exams_path, class: "dropdown-item" %>
          </div>
        </li>
      <% elsif %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Exam</a>
          <div class="dropdown-menu">
            <%= link_to "Exams list", students_exams_path, class: 'dropdown-item' %>
            <%= link_to "Review answered exam", students_log_exams_path, class: 'dropdown-item' %>
          </div>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Profile", edit_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, class: "nav-link", method: :delete %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      </li>
    <% end %>
  </ul>
</nav>