config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: "registrations"}
  namespace :teachers do
    resources :questions
    resources :log_exams, only: [:index, :show, :update, :destroy]
    resources :exams do
      collection do
        get :search
      end
    end
    resources :subjects, only: :show
  end

  namespace :students do
    resources :exams, only: :index
    resources :log_exams, except: [:new, :destroy]
  end

  root "application#index"
end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :exam_questions, dependent: :destroy
  has_many :questions, through: :exam_questions
  has_many :log_exams
  belongs_to :user

  validates :name, presence: true, uniqueness: {scope: :user},
    length: {maximum: Settings.validations.strings.max_length}
  validates :time_for_exam, presence: true
  validates :questions, presence: true
end

app/controllers/students/exams_controller.rb
module Students
  class ExamsController < ApplicationController
    def index
      redirect_to root_path unless current_user.student?
      @exams = Exam.all
    end
  end
end

app/controllers/teachers/exams_controller.rb
module Teachers
  class ExamsController < ApplicationController
    before_action :find_exam, only: [:show, :edit, :update, :destroy]
    before_action :check_permission

    def index
      @exams = Exam.all
    end

    def show ; end

    def new
      @exam = Exam.new
      @questions = Question.all
    end

    def create
      @exam = Exam.new exam_params
      @exam.user = current_user
      if @exam.save
        redirect_to teachers_exams_path
      else
        @questions = Question.all
        render :new
      end
    end

    def edit
      @questions = Question.all
    end

    def update
      if @exam.update_attributes(exam_params)
        redirect_to teachers_exam_path
      else
        @questions = Question.all
        render :edit
      end
    end

    def destroy
      @exam.destroy
      redirect_to teachers_exams_path
    end

    def search
      @exams = Question.find(params[:id]).exams
    end

    private
    def exam_params
      params.require(:exam).permit(:name, :time_for_exam, question_ids: [])
    end

    def find_exam
      @exam = Exam.find params[:id]
    end

    def check_permission
      case params[:action]
      when "index", "show"
        redirect_to root_path if cannot? :read, Exam
      when "new", "create"
        redirect_to root_path if cannot? :create, Exam
      when "edit", "update", "destroy"
        redirect_to root_path if @exam.user != current_user
      end
    end
  end
end

app/controllers/teachers/log_exams_controller.rb
module Teachers
  class LogExamsController < ApplicationController
    before_action :find_log_exam, only: [:show, :update, :destroy]
    before_action :check_permission

    def index
      @log_exams = LogExam.own_submitted_log_exams current_user.id
    end

    def show
      @exam = @log_exam.exam
    end

    def update
      @log_exam.update_attributes! status: :approved
      redirect_to teachers_exams_path
    end

    def destroy
      @log_exam.destroy
      redirect_to teachers_exams_path
    end

    private
    def find_log_exam
      @log_exam = LogExam.find params[:id]
    end

    def check_permission
      case params[:action]
      when "index", "show"
        redirect_to root_path if cannot? :read, LogExam
      when "update", "destroy"
        redirect_to root_path if @log_exam.exam.user != current_user
      end
    end
  end
end

app/controllers/teachers/questions_controller.rb
module Teachers
  class QuestionsController < ApplicationController
    before_action :find_question, only: [:show, :edit, :update, :destroy]
    before_action :check_permission

    def index
      @questions = Question.all
    end

    def show ; end

    def new
      @question = current_user.questions.new
      4.times {@question.answers.build}
    end

    def create
      @question = current_user.questions.new question_params
      if @question.save
        redirect_to teachers_questions_path
      else
        render :new
      end
    end

    def edit ; end

    def update
      if @question.update_attributes question_params
        redirect_to teachers_questions_path
      else
        render :edit
      end
    end

    def destroy
      @question.destroy
      redirect_to teachers_questions_path
    end

    private
    def question_params
      params.require(:question).permit(:subject_id, :content, :file,
        answers_attributes: [:is_true, :option, :id])
    end

    def find_question
      @question = Question.find params[:id]
    end

    def check_permission
      case params[:action]
      when "index", "show"
        redirect_to root_path if cannot? :read, Question
      when "new", "create"
        redirect_to root_path if cannot? :create, Question
      when "edit", "update", "destroy"
        redirect_to root_path if @question.user != current_user
      end
    end
  end
end

app/controllers/teachers/subjects_controller.rb
module Teachers
  class SubjectsController < ApplicationController
    def show
      @questions = Subject.find(params[:id]).questions
    end
  end
end

app/helpers/teachers/log_exams_helper.rb
module Teachers
  module LogExamsHelper
    def exam_requested exam_id
      @log_exams = LogExam.where exam_id: exam_id, teacher_id: current_user.id, status: :requested
    end
  end
end

app/views/teachers/exams/_exam_form.html.erb
<% if @exam.errors.any? %>
  <ul class="list-group list-group-flush">
    <% @exam.errors.full_messages.each do |msg| %>
      <li class="list-group-item allert alert-danger"><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<div class="form-group">
  <%= f.label :name, "Exam name" %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter exam name", value: exam.name %>
</div>

<div class="form-group">
  <%= f.label :time_for_exam %>
  <%= f.select :time_for_exam, options_for_select([15, 45, 90, 120, 180]), {prompt: "- Select -"}, {class: "form-control", selected: exam.time_for_exam} %>
</div>
<div class="form-group">
  <label>Select questions</label>
  <%= f.collection_check_boxes :question_ids, questions, :id, :content do |b| %>
    <div class="shadow-lg p-4 mb-4 bg-white" style="border-radius: 1em">
      <div class="custom-control custom-checkbox">
        <%= b.check_box class: "custom-control-input" %>
        <%= b.label class: "custom-control-label text-justify" %>
      </div>
      <div class="ml-4">
        <span class="badge badge-info">
          <%= link_to("Used #{pluralize(b.object.exams.count, "time")}",
            search_teachers_exams_path(id: b.object.id), class: "text-light") %>
        </span>
        <span class="badge badge-success"><%= link_to b.object.subject.name, teachers_subject_path(b.object.subject), class: "text-light"%></span>
        <span class="badge badge-info">
          <%= link_to "File attachment", b.object.file_url, class: "text-light" %>
        </span>
        <br>
        <div id="accordion-<%= b.object.id %>">
          <div class="card border-0">
            <div class="card-header pl-0 border-bottom-0">
              <a class="card-link text-dark" data-toggle="collapse" href="#collapse-answers-<%= b.object.id %>">
                Show answers
              </a>
            </div>
            <div id="collapse-answers-<%= b.object.id %>" class="collapse" data-parent="#accordion-<%= b.object.id %>">
              <div class="card-body p-0">
                <ul class="list-group list-group-flush">
                  <% b.object.answers.each do |answer| %>
                    <% if answer.is_true %>
                      <li class="list-group-item custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck" name="example1" disabled checked>
                        <label class="custom-control-label text-dark" for="customCheck"><%= answer.option %></label>
                      </li>
                    <% else %>
                      <li class="list-group-item">
                        <input type="checkbox" class="custom-control-input" id="customCheck" name="example1" disabled>
                        <label class="custom-control-label text-dark" for="customCheck"><%= answer.option %></label>
                      </li>
                    <% end %>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= f.submit "Submit", class: "btn btn-primary" %>

app/views/teachers/exams/_list_exams.html.erb
<% @exams.each do |exam| %>
  <div class="shadow-lg p-4 mb-4 bg-white" style="border-radius: 1em">
    <h3><%= link_to exam.name, teachers_exam_path(exam) %></h3>
    <small><%= pluralize exam.questions.count, "question" %>,
      updated by <%= exam.user.name %>
      at <%= time_ago_in_words exam.updated_at %></small>
    <br>
    <% if exam.user == current_user %>
      <% exam_requested(exam.id).each do |log_exam| %>
       <small class="clearfix">
          <%= log_exam.user.name %> sent request at <%= time_ago_in_words log_exam.created_at %>
          <%= link_to "Accept", teachers_log_exam_path(id: log_exam.id), method: :put %> /
          <%= link_to "Deny", teachers_log_exam_path(log_exam), method: :delete %>
       </small>
      <% end %>
      <ul class="breadcrumb pl-0" style="background-color: rgba(0,0,0,0)">
        <li class="breadcrumb-item"><%= link_to "Edit", edit_teachers_exam_path(exam) %></li>
        <li class="breadcrumb-item"><%= link_to "Delete", teachers_exam_path(exam), method: :delete %></li>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/teachers/exams/edit.html.erb
<%= form_for @exam, url: teachers_exam_path do |f| %>
  <h2 class="text-center mt-5">Edit exam</h2>
  <%= render "exam_form", f: f, exam: @exam, questions: @questions %>
<% end %>

app/views/teachers/exams/index.html.erb
<%= render "list_exams" %>

app/views/teachers/exams/new.html.erb
<%= form_for @exam, url: teachers_exams_path do |f| %>
  <h2 class="text-center mt-5">Create new exam</h2>
  <%= render "exam_form", f: f, exam: @exam, questions: @questions %>
<% end %>

app/views/teachers/exams/search.html.erb
<%= render "list_exams" %>

app/views/teachers/exams/show.html.erb
<% @exam.questions.each_with_index do |question, index| %>
  <div class="shadow-lg p-4 mb-4 bg-white" style="border-radius: 1em">
    <span><b>Question <%= index + 1 %>: </b></span>
    <span class="text-justify"><%= question.content %></span>
    <div class="ml-4">
      <%= link_to "File attachment", question.file_url %>
      <br>
      <div class="card border-0">
        <div>
          <div class="card-body p-0">
            <ul class="list-group list-group-flush">
              <% question.answers.each_with_index do |answer, index| %>
                <li class="list-group-item">
                  <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="customCheck-<%= question.id %>-<%= index %>" name="example" >
                    <label class="custom-control-label text-dark" for="customCheck-<%= question.id %>-<%= index %>"><%= answer.option %></label>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>